// pages/Home.js
import React, { useEffect, useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import "./Home.css";

const FEATURES = [
  {
    icon: "🗺️",
    title: "Live Safety Heatmap",
    desc: "Interactive map overlaid with AI-powered crime heat zones. See danger hotspots in real time before you step outside.",
    color: "#06b6d4",
  },
  {
    icon: "🤖",
    title: "AI Risk Analysis",
    desc: "Tap any location to get an instant safety score (0–100) generated by our trained crime-prediction model.",
    color: "#a78bfa",
  },
  {
    icon: "🚨",
    title: "One-Tap Emergency Alert",
    desc: "Send your GPS coordinates and an SOS message to emergency services or trusted contacts with a single tap.",
    color: "#ef4444",
  },
  {
    icon: "📈",
    title: "6-Month Trend Charts",
    desc: "Visualise how crime patterns have evolved over the past half-year with auto-generated bar charts per location.",
    color: "#f59e0b",
  },
  {
    icon: "🎙️",
    title: "Voice Search",
    desc: "Speak any address or area name. Our voice assistant geocodes it instantly and drops a safety pin on the map.",
    color: "#10b981",
  },
  {
    icon: "📞",
    title: "Crime Helplines",
    desc: "Country-specific emergency numbers always one click away — Police, Ambulance, Women's Helpline, and more.",
    color: "#f97316",
  },
];

const STEPS = [
  { num: "01", title: "Sign Up", desc: "Create your free account in seconds. We store your name, email and phone securely on your device.", icon: "📝" },
  { num: "02", title: "Allow Location", desc: "Grant location permission so SafeZone knows where you are and can load a personalised safety view.", icon: "📍" },
  { num: "03", title: "Explore the Map", desc: "Browse the AI heatmap, click any spot for a detailed risk score, peak hours and nearby services.", icon: "🗺️" },
  { num: "04", title: "Stay Safe", desc: "Set alerts, call emergency services, or share your location with trusted contacts from within the app.", icon: "🛡️" },
];

const STATS = [
  { value: "98%", label: "Prediction Accuracy" },
  { value: "50+", label: "City Datasets" },
  { value: "<2s", label: "Analysis Speed" },
  { value: "24/7", label: "Live Updates" },
];

function Home() {
  const [location, setLocation] = useState(null);
  const [riskScore, setRiskScore] = useState(null);
  const [, setTick] = useState(0);
  const navigate = useNavigate();
  const API_BASE = process.env.REACT_APP_API_BASE || "http://localhost:8000";

  const deterministicScore = (lat, lon) => {
    const x = Math.abs(Math.sin(lat * 12.9898 + lon * 78.233) * 43758.5453);
    return Math.floor((x - Math.floor(x)) * 100);
  };

  useEffect(() => {
    const stored = localStorage.getItem("userLocation");
    if (stored) {
      try {
        const loc = JSON.parse(stored);
        setLocation(loc);
        fetch(`${API_BASE}/analyze?lat=${loc.lat}&lon=${loc.lng}`)
          .then(r => r.ok ? r.json() : null)
          .then(j => setRiskScore(j ? (j.risk_score ?? j.score ?? deterministicScore(loc.lat, loc.lng)) : deterministicScore(loc.lat, loc.lng)))
          .catch(() => setRiskScore(deterministicScore(loc.lat, loc.lng)));
      } catch (_) { }
    }
    if (!stored && navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(pos => {
        const loc = { lat: pos.coords.latitude, lng: pos.coords.longitude };
        setLocation(loc);
        localStorage.setItem("userLocation", JSON.stringify(loc));
        setRiskScore(deterministicScore(loc.lat, loc.lng));
      }, () => { }, { timeout: 5000 });
    }
  }, []);

  const riskColor = riskScore === null ? "#06b6d4" : riskScore > 70 ? "#ef4444" : riskScore > 30 ? "#f97316" : "#10b981";
  const riskLabel = riskScore === null ? "—" : riskScore > 70 ? "HIGH RISK" : riskScore > 30 ? "MODERATE" : "SAFE";

  return (
    <div className="hp-page">

      {/* ══════════ HERO ══════════ */}
      <section className="hp-hero">
        <div className="hp-hero-bg" />
        <div className="hp-hero-content">
          <div className="hp-hero-badge">🛡️ AI-Powered Safety Platform</div>
          <h1 className="hp-hero-title">
            Know Your<br />
            <span className="hp-hero-title--accent">Safe Zone</span>
          </h1>
          <p className="hp-hero-desc">
            SafeZone AI analyses real crime datasets to give you an instant safety score for any location.
            Navigate smarter, stay safer, and react faster — powered by machine learning.
          </p>
          <div className="hp-hero-ctas">
            <button className="hp-btn hp-btn--primary" onClick={() => navigate("/map")}>
              🗺️ Open Safety Map
            </button>
            <button className="hp-btn hp-btn--outline" onClick={() => document.getElementById("hp-features").scrollIntoView({ behavior: "smooth" })}>
              Explore Features ↓
            </button>
          </div>

          {/* Live risk mini card */}
          {location && riskScore !== null && (
            <div className="hp-mini-card" style={{ borderColor: `${riskColor}40` }}>
              <div className="hp-mini-left">
                <div className="hp-mini-label">Your Location Risk</div>
                <div className="hp-mini-coords">📍 {location.lat.toFixed(3)}, {location.lng.toFixed(3)}</div>
              </div>
              <div className="hp-mini-score" style={{ color: riskColor }}>
                <div className="hp-mini-num">{riskScore}</div>
                <div className="hp-mini-badge" style={{ background: `${riskColor}25`, color: riskColor, border: `1px solid ${riskColor}40` }}>{riskLabel}</div>
              </div>
            </div>
          )}
        </div>

        {/* Hero illustration */}
        <div className="hp-hero-visual">
          <div className="hp-map-mockup">
            <div className="hp-map-header">
              <div className="hp-map-dot hp-map-dot--red" />
              <div className="hp-map-dot hp-map-dot--yellow" />
              <div className="hp-map-dot hp-map-dot--green" />
              <span className="hp-map-title">SafeZone Map</span>
            </div>
            <div className="hp-map-body">
              <div className="hp-map-grid" />
              {/* animated pins */}
              <div className="hp-pin hp-pin--danger" style={{ top: "30%", left: "45%" }}>
                <div className="hp-pin-dot" style={{ background: "#ef4444" }} />
                <div className="hp-pin-ring" style={{ borderColor: "#ef4444" }} />
                <div className="hp-pin-label" style={{ color: "#ef4444" }}>82 HIGH</div>
              </div>
              <div className="hp-pin hp-pin--warn" style={{ top: "55%", left: "25%" }}>
                <div className="hp-pin-dot" style={{ background: "#f97316" }} />
                <div className="hp-pin-ring" style={{ borderColor: "#f97316" }} />
                <div className="hp-pin-label" style={{ color: "#f97316" }}>57 MED</div>
              </div>
              <div className="hp-pin" style={{ top: "65%", left: "65%" }}>
                <div className="hp-pin-dot" style={{ background: "#10b981" }} />
                <div className="hp-pin-ring" style={{ borderColor: "#10b981" }} />
                <div className="hp-pin-label" style={{ color: "#10b981" }}>23 SAFE</div>
              </div>
              <div className="hp-pin" style={{ top: "22%", left: "70%" }}>
                <div className="hp-pin-dot" style={{ background: "#f97316" }} />
                <div className="hp-pin-ring" style={{ borderColor: "#f97316" }} />
                <div className="hp-pin-label" style={{ color: "#f97316" }}>64 MED</div>
              </div>
              {/* heatmap blobs */}
              <div className="hp-heat" style={{ top: "25%", left: "40%", background: "rgba(239,68,68,0.15)", width: 110, height: 110 }} />
              <div className="hp-heat" style={{ top: "48%", left: "20%", background: "rgba(249,115,22,0.12)", width: 90, height: 90 }} />
              <div className="hp-heat" style={{ top: "58%", left: "60%", background: "rgba(16,185,129,0.12)", width: 80, height: 80 }} />
            </div>
          </div>
        </div>
      </section>

      {/* ══════════ STATS STRIP ══════════ */}
      <section className="hp-stats">
        {STATS.map(s => (
          <div key={s.label} className="hp-stat">
            <div className="hp-stat-value">{s.value}</div>
            <div className="hp-stat-label">{s.label}</div>
          </div>
        ))}
      </section>

      {/* ══════════ FEATURES ══════════ */}
      <section className="hp-section" id="hp-features">
        <div className="hp-section-label">What We Offer</div>
        <h2 className="hp-section-title">Everything you need to stay safe</h2>
        <p className="hp-section-sub">Six powerful tools built into one seamless platform, available instantly after login.</p>
        <div className="hp-features-grid">
          {FEATURES.map(f => (
            <div key={f.title} className="hp-feature-card" style={{ "--fc": f.color }}>
              <div className="hp-feature-icon" style={{ background: `${f.color}18`, border: `1px solid ${f.color}30` }}>
                {f.icon}
              </div>
              <h3 className="hp-feature-title">{f.title}</h3>
              <p className="hp-feature-desc">{f.desc}</p>
              <div className="hp-feature-bar" style={{ background: `${f.color}30` }}>
                <div className="hp-feature-bar-fill" style={{ background: f.color }} />
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ══════════ HOW IT WORKS ══════════ */}
      <section className="hp-section hp-section--alt">
        <div className="hp-section-label">Simple Process</div>
        <h2 className="hp-section-title">How SafeZone AI works</h2>
        <p className="hp-section-sub">Get started in under 60 seconds. No complex setup — just sign up and stay safe.</p>
        <div className="hp-steps">
          {STEPS.map((step, i) => (
            <React.Fragment key={step.num}>
              <div className="hp-step">
                <div className="hp-step-num">{step.num}</div>
                <div className="hp-step-icon">{step.icon}</div>
                <h3 className="hp-step-title">{step.title}</h3>
                <p className="hp-step-desc">{step.desc}</p>
              </div>
              {i < STEPS.length - 1 && <div className="hp-step-arrow">→</div>}
            </React.Fragment>
          ))}
        </div>
      </section>

      {/* ══════════ VISUAL SHOWCASE ══════════ */}
      <section className="hp-section">
        <div className="hp-section-label">Feature Highlights</div>
        <h2 className="hp-section-title">See it in action</h2>
        <div className="hp-showcase-grid">

          {/* Card 1: Risk Score */}
          <div className="hp-showcase-card hp-showcase-card--tall">
            <div className="hp-showcase-inner hp-showcase-inner--dark">
              <div style={{ opacity: 0.6, fontSize: "0.75rem", textTransform: "uppercase", letterSpacing: 1, marginBottom: "1rem", color: "#94a3b8" }}>AI Risk Score</div>
              <div style={{ fontSize: "5rem", fontWeight: 900, color: "#ef4444", lineHeight: 1 }}>78</div>
              <div style={{ fontSize: "0.8rem", color: "#ef4444", marginTop: "0.5rem", background: "rgba(239,68,68,0.15)", padding: "0.3rem 0.7rem", borderRadius: 6, display: "inline-block" }}>HIGH RISK</div>
              <div style={{ marginTop: "1.5rem", display: "flex", gap: "0.5rem", flexDirection: "column" }}>
                {[["Theft Risk", 80], ["Assault Risk", 68], ["Vandalism", 55]].map(([l, v]) => (
                  <div key={l} style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
                    <span style={{ width: 80, fontSize: "0.75rem", color: "#94a3b8" }}>{l}</span>
                    <div style={{ flex: 1, height: 6, background: "rgba(255,255,255,0.07)", borderRadius: 3, overflow: "hidden" }}>
                      <div style={{ width: `${v}%`, height: "100%", background: "#ef4444", borderRadius: 3 }} />
                    </div>
                    <span style={{ fontSize: "0.72rem", color: "#ef4444", width: 28 }}>{v}%</span>
                  </div>
                ))}
              </div>
            </div>
            <div className="hp-showcase-label">Instant Risk Breakdown</div>
          </div>

          {/* Card 2: Emergency */}
          <div className="hp-showcase-card">
            <div className="hp-showcase-inner" style={{ background: "linear-gradient(135deg, rgba(239,68,68,0.15), rgba(220,38,38,0.05))", border: "1px solid rgba(239,68,68,0.2)" }}>
              <div style={{ fontSize: "2.5rem", marginBottom: "1rem" }}>🚨</div>
              <div style={{ fontWeight: 800, fontSize: "1.1rem", marginBottom: "0.5rem" }}>Emergency Alert</div>
              <div style={{ fontSize: "0.85rem", color: "#94a3b8", marginBottom: "1.25rem" }}>One tap sends your GPS location to emergency services</div>
              <div style={{ background: "linear-gradient(135deg,#ef4444,#dc2626)", borderRadius: 10, padding: "0.75rem 1.25rem", fontWeight: 700, color: "white", fontSize: "0.9rem", display: "inline-block", boxShadow: "0 4px 14px rgba(239,68,68,0.4)" }}>
                🚨 Send SOS Alert
              </div>
              <div style={{ display: "flex", gap: "0.5rem", marginTop: "0.9rem", justifyContent: "center" }}>
                <span style={{ background: "rgba(239,68,68,0.15)", border: "1px solid rgba(239,68,68,0.3)", color: "#fca5a5", borderRadius: 6, padding: "0.3rem 0.6rem", fontSize: "0.75rem" }}>📞 100</span>
                <span style={{ background: "rgba(239,68,68,0.15)", border: "1px solid rgba(239,68,68,0.3)", color: "#fca5a5", borderRadius: 6, padding: "0.3rem 0.6rem", fontSize: "0.75rem" }}>📞 112</span>
                <span style={{ background: "rgba(239,68,68,0.15)", border: "1px solid rgba(239,68,68,0.3)", color: "#fca5a5", borderRadius: 6, padding: "0.3rem 0.6rem", fontSize: "0.75rem" }}>📞 1091</span>
              </div>
            </div>
            <div className="hp-showcase-label">Emergency Services</div>
          </div>

          {/* Card 3: Voice */}
          <div className="hp-showcase-card">
            <div className="hp-showcase-inner" style={{ background: "linear-gradient(135deg, rgba(16,185,129,0.12), rgba(6,182,212,0.05))", border: "1px solid rgba(16,185,129,0.2)" }}>
              <div style={{ fontSize: "2.5rem", marginBottom: "1rem" }}>🎙️</div>
              <div style={{ fontWeight: 800, fontSize: "1.1rem", marginBottom: "0.5rem" }}>Voice Search</div>
              <div style={{ fontSize: "0.85rem", color: "#94a3b8", marginBottom: "1.25rem" }}>Say any location and get its risk score in seconds</div>
              <div style={{ display: "flex", gap: "8px", alignItems: "center", background: "rgba(16,185,129,0.08)", border: "1px solid rgba(16,185,129,0.2)", borderRadius: 10, padding: "0.6rem 1rem" }}>
                <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#10b981", animation: "op-pulse 1.5s ease-in-out infinite" }} />
                <span style={{ color: "#86efac", fontSize: "0.85rem", fontStyle: "italic" }}>"Is Connaught Place safe at night?"</span>
              </div>
              <div style={{ marginTop: "0.75rem", background: "rgba(6,182,212,0.08)", border: "1px solid rgba(6,182,212,0.15)", borderRadius: 8, padding: "0.5rem 0.75rem", fontSize: "0.8rem", color: "#94a3b8", textAlign: "left" }}>
                📍 Connaught Place, New Delhi — <span style={{ color: "#f97316", fontWeight: 700 }}>Risk Score: 58 (Moderate)</span>
              </div>
            </div>
            <div className="hp-showcase-label">Hands-Free Search</div>
          </div>

          {/* Card 4: Trend */}
          <div className="hp-showcase-card hp-showcase-card--wide">
            <div className="hp-showcase-inner hp-showcase-inner--dark">
              <div style={{ opacity: 0.6, fontSize: "0.75rem", textTransform: "uppercase", letterSpacing: 1, marginBottom: "1rem", color: "#94a3b8" }}>📈 6-Month Crime Trend</div>
              <div style={{ display: "flex", alignItems: "flex-end", gap: "8px", height: 80 }}>
                {[40, 55, 48, 70, 63, 78].map((v, i) => (
                  <div key={i} style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 4 }}>
                    <div style={{ width: "100%", height: `${v}%`, background: v > 60 ? "rgba(239,68,68,0.7)" : "rgba(249,115,22,0.7)", borderRadius: "4px 4px 0 0", transition: "height 0.5s ease" }} />
                    <span style={{ fontSize: "0.65rem", color: "#64748b" }}>{["J", "F", "M", "A", "M", "J"][i]}</span>
                  </div>
                ))}
              </div>
              <div style={{ marginTop: "0.75rem", fontSize: "0.8rem", color: "#94a3b8" }}>Crime incidents are <span style={{ color: "#ef4444", fontWeight: 700 }}>rising 12%</span> — stay vigilant in evenings</div>
            </div>
            <div className="hp-showcase-label">Historical Trend Analysis</div>
          </div>
        </div>
      </section>

      {/* ══════════ CTA BANNER ══════════ */}
      <section className="hp-cta">
        <div className="hp-cta-glow" />
        <div className="hp-cta-content">
          <h2 className="hp-cta-title">Your safety starts here</h2>
          <p className="hp-cta-desc">Join SafeZone AI today and get real-time crime intelligence for any location in your city.</p>
          <div style={{ display: "flex", gap: "1rem", justifyContent: "center", flexWrap: "wrap" }}>
            <button className="hp-btn hp-btn--primary hp-btn--lg" onClick={() => navigate("/map")}>
              🗺️ Open Safety Map
            </button>
            <Link to="/signup" className="hp-btn hp-btn--ghost hp-btn--lg">Create Free Account →</Link>
          </div>
        </div>
      </section>

      {/* ══════════ FEEDBACK CALLOUT ══════════ */}
      <section className="hp-section hp-section--alt">
        <div className="hp-section-label">User Feedback</div>
        <h2 className="hp-section-title">Help us improve SafeZone</h2>
        <p className="hp-section-sub">Your ratings and suggestions help make SafeZone AI better for everyone.</p>
        <div style={{ textAlign: "center", marginTop: "2rem" }}>
          <div style={{ fontSize: "3rem", marginBottom: "1rem" }}>⭐🌟⭐</div>
          <button className="hp-btn hp-btn--primary" onClick={() => navigate("/feedback")}>
            ⭐ Rate Our App & Feedback
          </button>
        </div>
      </section>

      {/* ══════════ FOOTER ══════════ */}
      <footer className="hp-footer">
        <div className="hp-footer-brand">
          <span className="hp-footer-badge">SZ</span>
          <span>SafeZone AI</span>
        </div>
        <p className="hp-footer-copy">© {new Date().getFullYear()} SafeZone AI — AI-powered community safety platform</p>
        <div className="hp-footer-links">
          <span>🛡️ Privacy First</span>
          <span>📵 No Ads</span>
          <span>🔓 Open Data</span>
        </div>
      </footer>
    </div>
  );
}

export default Home;